### PR TITLE
Add sharing for LegendSet

### PR DESCRIPTION
**Pull request by vietnguyen**

### CODE REVIEW

**Comment by ceciliapersson** [comment]
@vietnguyen Will this be included in 2.25? If so, please let me know so I can documented the new functionality.

**Comment by vietnguyen** [comment]
@ceciliapersson yes, it will be included in 2.25, waiting for @mortenoh  or @larshelge  to merge.

**Comment by ceciliapersson** [comment]
Doc issue created: https://github.com/dhis2/dhis2-docs/issues/298

**Comment by ceciliapersson** [comment]
Doc has been updated.

**Pull request merged**
