### PR TITLE
Format comments

### PR DESCRIPTION
**Pull request by enricocolasante**
Avoid to break comments into multiple lines when is not necessary

### CODE REVIEW

**Review by jbee — APPROVED** [review]

**Comment by larshelge** [comment]
On second thought - maybe it is better to keep Javadoc at 80 characters? Java itself and others are using 80 character width, and I think it improves readability to avoid long lines. Maybe we should leave it as is? I would vote for that I think.

**Comment by jbee** [comment]
I do agree with the @larshelge that the unintended side effect of all javadoc now "nesting" so the blocks get 80 width instead of all ending at 80 character line is not very appealing to me. I'd think there should be a better way to just affect inline comments. Alternative is to always put the comment on the line above. Not ideal but works and since the case we try to fix is rare we maybe should not make the fix on the back of a case that is very common.

**Comment by enricocolasante** [comment]
You are both right.
I got lost in solving the conflicts, the actual solution is not to extend the line of comments to 120 but to make it count from the beginning of the comment, so the inline comments can be long up to 80 chars.
Check the first file in the Files changed section and have a look at how the comments look now.
They changed a little bit, I think they are just a couple of chars longer, I think because the space at the beginning now does not count in the 80 chars.
Anyway, have a look now and tell me if it is ok to have them like this

**Review by jbee — COMMENTED** [review]
As much as I would like inline comments to work I think this still has the issue that the javadoc will now come out like this:

```java

/**
 * Some text that ends at 80 ...................................................say here
 **/
class Foo {
   /**
     * Some text that ends at 80+2 ...................................................say here
     **/
   String field;
   
  static class Bar {
     /**
       * Some text that ends at 80 + 4 ...................................................say here
     **/
     String anotherField;
  }
}

```
and so forth. If I understood @larshelge right we don't want this. 

I'd think what we actually would want is to have no limit for inline comments at all but have current rules (all javadoc ends at 80 characters line from zero) apply to javadoc.

**Review by netroms — APPROVED** [review]

**Pull request closed without merging**
