### PR TITLE
[DHIS2-5675] Fix error enter data values using the Persian or Nepali calendar

### PR DESCRIPTION
**Pull request by vietnguyen**
https://jira.dhis2.org/browse/DHIS2-5675

Fix error when passing negative value to plusMonths() or plusDays() in custom Calendar classes.

After this is merged,  i will backport down to 2.29

### CODE REVIEW

**Comment by vietnguyen** [comment]
Added unit tests

**Comment by jason-p-pickering** [comment]
Thanks a lot for the quick fix. 

I will test and let you know how it goes.

**Comment by jason-p-pickering** [comment]
@vietnguyen There are still two PRs (now more than a year old) related to the Persian calendar, which have not been merged. https://github.com/dhis2/dhis2-core/pull/1365. This may be part of the reason why these other bugs popped up. Could you have a look at them and see if they are also relevant?

**Comment by vietnguyen** [comment]
> @vietnguyen There are still two PRs (now more than a year old) related to the Persian calendar, which have not been merged. #1365. This may be part of the reason why these other bugs popped up. Could you have a look at them and see if they are also relevant?

@jason-p-pickering I will check that PR, do you have a jira issue for it ? just want to know which error it's fixing.

**Pull request merged**
