### PR TITLE
fix: token search with non ASCII alphanumeric characters [DHIS2-10323]

### PR DESCRIPTION
**Pull request by jbee**
### Summary
Token based searches would strip all non-ASCII alphanumeric characters effectively preventing all scripts with other or additional letters from working correctly. This PR changes the kept characters from `a-zA-Z0-9` to all unicode script letters as well as 0-9.  

### Automatic Testing
Added a test scenario that adds a OU with a Cyrillic name and searches for it using token search like the Maintenance app does.

### Manual Testing
* create a metadata object with name `Кириллица`
* make sure other objects of the same type exist, either because they are already in the database or create them
* open Maintenance app and search for `Кириллица`
* check only the created item is listed
* check that searching for other terms matches the expected set of objects

### CODE REVIEW

**Comment by larshelge** [comment]
Very nice, great that you figured this out @jbee .

Could we perhaps add a unit test to verify the behavior?

**Comment by jbee** [comment]
@larshelge This will require full integration tests as it uses custom database function but we can add one of those.

**Comment by jbee** [comment]
@larshelge Test added

**Comment by vietnguyen** [comment]
@jbee  thanks for fixing this.

There is a method ` public static <T> boolean test( List<T> args, T testValue, String targetValue, boolean caseSensitive,
        MatchMode matchMode )` in class `TokenUtils` which might also have the same issue.

The `test` method is used in `InMemoryQueryEngine.runQuery()`.

**Comment by jbee** [comment]
@vietnguyen Thanks for pointing this out. I can make another PR for that.

**Review by vietnguyen — APPROVED** [review]

**Review by mortenoh — APPROVED** [review]

**Pull request merged**
