### PR TITLE
chore: create dev build script

### PR DESCRIPTION
**Pull request by amcgee**
This adds a development build script which does the following:

1. Runs `mvn` locally (so faster than building in Docker)
2. Builds a Docker image with the resulting WAR file
3. (optionally) runs `docker cluster up` with the passed cluster name to replace the Core service image in a running `d2 cluster` instance.

Usage:
`./dhis-2/build-dev.sh mytestcluster`

System requirements:
- bash @ > 4 (notably not default on Mac)
- coreutils for sha256sum and md5sum (not default on Mac)
- Maven (`mvn`)
- Docker

### CODE REVIEW

**Review by HendrikThePendric — APPROVED** [review]
👍  Code is looking good, but perhaps we should include some info about system requirements in the docs too? Having said that, I think that's actually out-of-scope fro this PR, since this information would relate to (some of) the existing bash scripts too.

**Review by stian-sandvold — APPROVED** [review]

**Comment by vilkg** [comment]
I am not sure if anyone from the backend team is using the cluster, but I think it's great that you added it; even without spinning up the cluster part, this PR is quite useful. One question though: when spinning up the cluster, will "dev" database be used? That could be a problem when using this on older branches, or even 2.35, once the dev is on 2.36.

**Comment by amcgee** [comment]
> when spinning up the cluster, will "dev" database be used? That could be a problem when using this on older branches, or even 2.35, once the dev is on 2.36.

@vilkg good question!  The `d2 cluster up` command here won't seed any database.  It will spin up an empty DB if one doesn't exist, but in most cases I use this with an already-running (and already-seeded) cluster.  It just replaces the Core image, so the DB and everything else stay the same.  You could very easily spin up i.e. a 2.34.1 cluster and then replace the Core service with a custom build to test something for the 2.34.2 patch, for instance.

```sh
d2 cluster up 34test --dhis2-version 2.34.1 --db-version 2.34 --seed
./dhis-2/build-dev.sh 34test
```

**Comment by amcgee** [comment]
Any ideas why the SonarCloud Code Analysis check appears to be stalled?  Hasn't run in about 24 hours...  @vilkg

**Comment by vilkg** [comment]
Thanks for the clarification! 

> Any ideas why the SonarCloud Code Analysis check appears to be stalled? Hasn't run in about 24 hours... @vilkg

Yes, there's apparently [a bug in sonarcloud/GH actions](https://community.sonarsource.com/t/sonarcloud-code-analysis-expected-onoging-issues/28154), where an incorrect commit sha is being picked up by analysis. We will have to ignore this check on this PR.

**Review by vilkg — APPROVED** [review]

**Comment by amcgee** [comment]
Force-merging this despite the unrelated stalled Action check - safe, since this is purely a devtool and non-functional.

**Pull request merged**
