### PR TITLE
fix: (2.35) Lazy exception while loading UserGroupAccess for Attribute [DHIS2-8868]

### PR DESCRIPTION
**Pull request by zubaira**
image

@mortenoh performance test results

### CODE REVIEW

**Review by enricocolasante — CHANGES_REQUESTED** [review]
@mortenoh @jbee This annotation was removed here https://github.com/dhis2/dhis2-core/pull/7266
I am not sure why and it seems that it will not work if the attribute is not present in cache and the calling method didn't open a transaction.

**Review by jbee — APPROVED** [review]

**Comment by mortenoh** [comment]
> @mortenoh @jbee This annotation was removed here #7266
> I am not sure why and it seems that it will not work if the attribute is not present in cache and the calling method didn't open a transaction.

This was removed since it was causing heavy performance issues, I don't think we should simply add this back. The main problem was with nested transaction (mixing read-write and read-only ones), we might get away with using a read-write tx instead.

**Comment by jbee** [comment]
@mortenoh do you know if this was before or after we straighten out most of the `@Transactional` annotations?

**Comment by stian-sandvold** [comment]
@mortenoh and @zubaira could you discuss @mortenoh s comment here and find a suitable solution? From the PR it looks unresolved

**Comment by vilkg** [comment]
The results from the test attached here are not representative, because the tests didn't cover the endpoint that was problematic before and there is not enough metadata to test this on. Endpoint `/api/optionSets/ID?fields=*`. Metadata: 15 attributes, 1 option set and 200k options. I'll set up some random metadata on the performance test db.

**Comment by vilkg** [comment]
image
It's clear that we need another solution to solve this. That's the performance of getting an option set that has many options and attributes (Scenario that Morten had in Laos)

**Comment by zubaira** [comment]
fix causes performance issues.

**Pull request closed without merging**
