### PR TITLE
2.37 dhis2 4361 cascade delete of interpretations

### PR DESCRIPTION
**Pull request by d-bernat**

### CODE REVIEW

**Review by maikelarabori — COMMENTED** [review]
Hi @d-bernat , the code looks good to me.
But in the story, they mention something around "warning" messages to the user and user access and user groups. Are those points being removed from the scope? Just want to be sure before approving it.

Thanks

**Comment by d-bernat** [comment]
> Hi @d-bernat , the code looks good to me.
> But in the story, they mention something around "warning" messages to the user and user access and user groups. Are those points being removed from the scope? Just want to be sure before approving it.
> 
> Thanks

I think any warning message will be shown by FrontEnd. Because the FrontEnd has sufficient data (data access) to know there are some interpretations hanging on Visualization (Map),  it should not be necessary to open any new endpoint. Am I right?

**Comment by maikelarabori** [comment]
> > Hi @d-bernat , the code looks good to me.
> > But in the story, they mention something around "warning" messages to the user and user access and user groups. Are those points being removed from the scope? Just want to be sure before approving it.
> > Thanks
> 
> I think any warning message will be shown by FrontEnd. Because the FrontEnd has sufficient data (data access) to know there are some interpretations hanging on Visualization (Map), it should not be necessary to open any new endpoint. Am I right?

Hey @d-bernat , yes, that would be possible. I'm just wondering if the requirements want to have this restriction enforced, otherwise, the endpoint will always cascade. It was not clear to me.
We have also the DashboardItem that can be associated with a Visualization, per this comment:
https://jira.dhis2.org/browse/DHIS2-4361?focusedCommentId=18512&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-18512

But again, it's just my view based on the story and comments on the JIRA.

**Comment by d-bernat** [comment]
> > > Hi @d-bernat , the code looks good to me.
> > > But in the story, they mention something around "warning" messages to the user and user access and user groups. Are those points being removed from the scope? Just want to be sure before approving it.
> > > Thanks
> > 
> > 
> > I think any warning message will be shown by FrontEnd. Because the FrontEnd has sufficient data (data access) to know there are some interpretations hanging on Visualization (Map), it should not be necessary to open any new endpoint. Am I right?
> 
> Hey @d-bernat , yes, that would be possible. I'm just wondering if the requirements want to have this restriction enforced, otherwise, the endpoint will always cascade. It was not clear to me.
> We have also the DashboardItem that can be associated with a Visualization, per this comment:
> https://jira.dhis2.org/browse/DHIS2-4361?focusedCommentId=18512&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-18512
> 
> But again, it's just my view based on the story and comments on the JIRA.


> > > Hi @d-bernat , the code looks good to me.
> > > But in the story, they mention something around "warning" messages to the user and user access and user groups. Are those points being removed from the scope? Just want to be sure before approving it.
> > > Thanks
> > 
> > 
> > I think any warning message will be shown by FrontEnd. Because the FrontEnd has sufficient data (data access) to know there are some interpretations hanging on Visualization (Map), it should not be necessary to open any new endpoint. Am I right?
> 
> Hey @d-bernat , yes, that would be possible. I'm just wondering if the requirements want to have this restriction enforced, otherwise, the endpoint will always cascade. It was not clear to me.
> We have also the DashboardItem that can be associated with a Visualization, per this comment:
> https://jira.dhis2.org/browse/DHIS2-4361?focusedCommentId=18512&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-18512
> 
> But again, it's just my view based on the story and comments on the JIRA.

Yeah, maybe you are right, let me check this thing with with Item included in Dashboard....

**Review by maikelarabori — APPROVED** [review]
The code looks good @d-bernat :+1:

**Review by larshelge — APPROVED** [review]

**Comment by larshelge** [comment]
I would say lets do this in steps, where the first one is to remove interpretations to fix the immediate problem. We can add a separate issue/PR for warnings.

**Review by larshelge — APPROVED** [review]

**Pull request merged**
