### PR TITLE
Adjust how active users are calculated in statistics snapshot

### PR DESCRIPTION
**Pull request by jason-p-pickering**

### CODE REVIEW

**Comment by jbee** [comment]
Still waiting on green light from Scott on this.

**Comment by jbee** [comment]
Pinged Stian again on this.

**Review by jbee — APPROVED** [review]
We have green light on this PR :rocket: 
Just need to make check the tests pass.

**Comment by jason-p-pickering** [comment]
@jbee I got this to go green after triggering the API test run again.

**Pull request merged**
