### PR TITLE
fix: Ensure a weekly period does not come on two years

### PR DESCRIPTION
**Pull request by abyot**

### CODE REVIEW

**Comment by Philip-Larsen-Donnelly** [comment]
@vietnguyen @stian-sandvold It would be great if you could review this ASAP,
and @abyot assuming the reviewers are happy, could you please prepare backports to 2.33 (ideally by tomorrow! for the 2.33.4 freeze) and 2.34 (for release fairly soon)?

**Comment by Philip-Larsen-Donnelly** [comment]
@abyot @stian-sandvold  
Is it possible to get this ported to `patch/2.33.4`?
(and eventually 2.33 and 2.34)

**Comment by stratosilva** [comment]
Hi guys.
We have an issue with this new commit #5585 but can't be reproduced in demo server. You may not do anything about it, but at least I found sensible to warn you in case this happens to other users.

The line of code:
`var isNextYearWeek = (startDate.formatDate(this.format) <= nextYearStartDate) && (nextYearStartDate <= endDate.formatDate(this.format)); `
Evaluates to true despite having the following values:
```
nextYearStartDate = 30-12-2019
startDate = 25-03-2019
endDate = 31-03-2019
```
So the selector is populated only with some weeks.
image

It also happens for 2020.

Any ideas why isNextYearWeek could end up evaluating to true even though the startDate and endDates are still far from the nextYearStartDate? I debugged the code and this is what I found. I saw some comments in Stackoverflow saying that, in order to compare dates, it is better to convert them to numbers (for example unixtimestamp). Any thoughts? I suspect tomcat / JVM issue on the way this code is interpreted. 

FYI, our server is running:
Server version: Apache Tomcat/7.0.76
Server built:  Mar 12 2019 10:11:36 UTC
OS Name:    Linux
OS Version:   3.10.0-957.12.2.el7.x86_64
JVM Version:  1.8.0_212-b04
JVM Vendor:   Oracle Corporation

**Comment by stratosilva** [comment]
Normally is is best to convert to numeric when comparing dates... I suspect that our JVM is not interpreting this comparison well. I have changed the code to use unix timestamps respecting the same conditions and it works. You can see here:

First, the loop stops at 25/03/2019, but you can see that date comparison gives true (that is why it breaks the loop) but the numeric comparison continues to be false -> Correct behavior
image

So if I change the if to use numericIsNextYearWeek instead, it works as expected:
image

**Pull request merged**
