### PR TITLE
[2.26] Fix in event reports page to display available items properly

### PR DESCRIPTION
**Pull request by harikrishnakanchi**
On initial load of event reports page, both data elements and program indicators are listed on selection of program under aggregated values tab. This fix will filter program indicator on selection of program.

### CODE REVIEW

**Comment by harikrishnakanchi** [comment]
@larshelge any updates on this pull request?

**Comment by janhenrikoverland** [comment]
We are looking to make a proper solution for program indicators, ref: https://jira.dhis2.org/browse/DHIS2-1496

**Comment by davidoh** [comment]
@janhenrikoverland - I understand that we wouldn't want to invest significant effort into fixing the issue given the plans to develop a proper solution for program indicators, however @harikrishnakanchi's pull request is a one-line fix.

Furthermore this issue is causing significant usability issues to our end users because the list of program indicators is being mixed up with the list of data elements, making it difficult for them to find the data element they are looking for. From our perspective we have Hari's fix on our own custom build of DHIS2, however this does not allow other DHIS2 implementations to benefit from the fix. Can we reconsider merging this pull request?

**Comment by janhenrikoverland** [comment]
It's okay for 2.26. Merged.

**Comment by harikrishnakanchi** [comment]
Hi @janhenrikoverland,
Can you merge #741  pull request as well. This is a back-port for 2.25.

**Pull request merged**
