### PR TITLE
fix: (2.36) Data Element form name not shown in the forms

### PR DESCRIPTION
**Pull request by zubaira**

### CODE REVIEW

**Comment by larshelge** [comment]
Do you think you could add a description of the thinking behind this fix @zubaira ?

**Comment by Bekkalizer** [comment]
@zubaira It seems that the formName property was working correctly, but displayFormName was not. See the last comment in the [jira issue](https://jira.dhis2.org/browse/DHIS2-11144). The code change on the PR didn't seem to address that part?

**Comment by zubaira** [comment]
> @zubaira It seems that the formName property was working correctly, but displayFormName was not. See the last comment in the [jira issue](https://jira.dhis2.org/browse/DHIS2-11144). The code change on the PR didn't seem to address that part?

@Bekkalizer yes `displayFormName` property was not working fine because this property was not getting populated from `BaseIdentifiableObject.formName` and the reason was `DataElement` explicitly had `formName` variable.

**Review by Bekkalizer — APPROVED** [review]
Makes sense - LGTM!

**Comment by larshelge** [comment]
Right, thanks @zubaira . It is actually `BaseNameableObject` which has formName now, but that is just a detail. Good catch.

**Review by stian-sandvold — APPROVED** [review]

**Pull request merged**
