### PR TITLE
fix: [WIP] (2.38) log event data value audit history (#10164)

### PR DESCRIPTION
**Pull request by zubaira**

### CODE REVIEW

**Comment by vilkg** [comment]
is this still WIP?

**Comment by zubaira** [comment]
> is this still WIP?

i might close this PR as this was a quick fix for audit history. Now we have decided to work on a proper solution that involves changes on both frontend ( capture app) and backend side ( preheater).

**Comment by vilkg** [comment]
So should we close @zubaira ?

**Comment by zubaira** [comment]
Closing this PR because a more comprehensive solution is required.

**Pull request closed without merging**
