### PR TITLE
ci: Run tests on Java 11

### PR DESCRIPTION
**Pull request by vilkg**

### CODE REVIEW

**Comment by mortenoh** [comment]
Hi, there are some complications here... @netroms is working on a fix for jdk9+, so i guess we should merge with master after that lands (and hopefully this will compile/test fine again then)

**Comment by netroms** [comment]
> Hi, there are some complications here... @netroms is working on a fix for jdk9+, so i guess we should merge with master after that lands (and hopefully this will compile/test fine again then)

My fix is merged with master now.

**Comment by mortenoh** [comment]
@vilkg could you merge with master (there are some conflicts) and see if this works now?

**Comment by vilkg** [comment]
Thanks for the reminder @mortenoh. The unit tests are still failing https://github.com/dhis2/dhis2-core/runs/557271827

**Comment by mortenoh** [comment]
@netroms could you have another look? I see among other things IllegalAccess, maybe we need to add some parameters to JRE? something like `–illegal-access=permit`

**Comment by vilkg** [comment]
@mortenoh @netroms, 

unit tests are still failing after recent merge of master.

**Comment by vilkg** [comment]
opened new PR: #6010

**Pull request closed without merging**
