### PR TITLE
fix: DHIS2-10766: api test fix

### PR DESCRIPTION
**Pull request by maikelarabori**
Adding AGGREGATE for data elements to match the new rule added to the filtering.

### CODE REVIEW

**Comment by vilkg** [comment]
@maikelarabori , can you share the jira to the original issue for that new rule? [This one](https://jira.dhis2.org/browse/DHIS2-10766) seems to only be about duplicated elements, but I don't see anywhere in the description that the contract should be changed and only AGGREGATE elements should be returned

**Comment by maikelarabori** [comment]
Hi @vilkg ,
my original PR mentions it. I found this issue while testing the fix for the duplicating rows.

Original PR:
https://github.com/dhis2/dhis2-core/pull/7801

Just thought that wouldn't be necessary to create a JIRA for this small issue. There is no JIRA for this specific issue.

There is no change in the contract either. I just added a missed rule that will bring only data elements of _domainType_ AGGREGATE.

**Comment by vilkg** [comment]
I think we need an issue for this, as this changes the endpoint behavior. If someone complains, we need to have a traceable explanation why we changed it. Also, a doc change that describes the rule. What do you think @Philip-Larsen-Donnelly ?

**Comment by maikelarabori** [comment]
The original ticket is: https://jira.dhis2.org/browse/DHIS2-9934

You can go to the ticket and check item 10):

_10) The /dataItems endpoint will bring only data items that are defined as an **aggregatable** type._

And this is already documented, you can find it in my other PR:
https://github.com/dhis2/dhis2-docs/pull/630/files

You can look for: _The /dataItems endpoint will bring only data items that are defined as **aggregatable** type._

Regarding open a new ticket, again, as it was a small requirement missed from the original ticket I thought that it would not be needed.

Let me know if you guys want me to remove this fix, create a new JIRA, create another PR and ask for another round of code review.

_Talking about tracking back PR, I agree. But then we have to enforce it on everyone. There are many PRs regarding "refactoring" and "clean-up" without any JIRA associated that caused issues in the past and will keep causing in the future. We have to enforce a JIRA ticket for all PRs even very small ones. Or we apply it globally or we don't. Just my two cents._

**Comment by vilkg** [comment]
I totally agree that it should be enforced. And it is a general rule, which I think is followed by most people. I only saw this because your previous PR failed the tests and the fact that the fix is fixing the tests shows a change in functionality. 

Great that you added documentation, and given that the change is described in the original issue, I think it's okay. The original issue was closed without testing, but I see that Phil approved it for the release, so I hope it will be tested.

**Review by vilkg — APPROVED** [review]

**Comment by maikelarabori** [comment]
> I totally agree that it should be enforced. And it is a general rule, which I think is followed by most people. I only saw this because your previous PR failed the tests and the fact that the fix is fixing the tests shows a change in functionality.
> 
> Great that you added documentation, and given that the change is described in the original issue, I think it's okay. The original issue was closed without testing, but I see that Phil approved it for the release, so I hope it will be tested.

**Pull request merged**
