### PR TITLE
fix: Replace core icons with consistent, modern, flat icons

### PR DESCRIPTION
**Pull request by dburka**
I took a few days and took a stab at redesigning the core DHIS2 icons in a consistent flat style. See below for the original vectors of all of the graphics — SVGs could easily be exported from the Figma file.

**Meaning:**
I am not 100% clear on the precise contextual meaning of all of the icons and could easily have created symbols that do not accurately reflect the section of DHIS2. Please suggest changes and improvements.

**Technical:**
The PNGs are considerably smaller file sizes than the original graphics, mostly because they are flatter/simpler. These are also saved at the original scale from the /icons/ directory and also at @2x double scale for retina displays. I looked at the HTML in DHIS2 and it looks like sizes are not explicitly set for the icons in many places, which would need to be changed to use the @2x icons.

**Use:**
These are either drawn from scratch or based off of a CC0 open source collection of vector icons. I give these freely to use however you wish in a completely public domain way. If you just don't want to use these icons, please don't feel any pressure.

**Original vectors:**
Figma link with the vector graphics of all of the icons. Please feel free to edit and use as you see fit.
https://www.figma.com/file/mbsBVYXECIOl5E0kkGAiC2/DHIS2-Icons-and-Logos?node-id=1%3A2440&viewport=597%2C535%2C1.1560002565383911

### CODE REVIEW

**Comment by dburka** [comment]
Here is a PNG of all of the icons as a set. Again, this is from the Figma file, linked above. 
image

**Comment by dburka** [comment]
Changed the PR title. Sorry, "semantic PR titles" is new to me!

**Comment by stian-sandvold** [comment]
@cooper-joe is following up with this. Closing as suggested by Joe.

**Comment by cooper-joe** [comment]
Hey @dburka, I appreciate the work that went into this! As I mentioned in another meeting were we in, we're currently looking into a building a simpler icon system for all DHIS2 applications. The simplicity is important, as it will allow external developers to create icons that look consistent with the DHIS2 platform. This isn't 100% decided yet, so I'll keep this submission in mind too, there's some nice visualizations here 👍

**Pull request closed without merging**
