### PR TITLE
refactor: Apache Artemis use in-vm connector [DHIS2-10592]

### PR DESCRIPTION
**Pull request by mortenoh**
[DHIS2-10592](https://jira.dhis2.org/browse/DHIS2-10592)

### CODE REVIEW

**Review by netroms — APPROVED** [review]

**Comment by mortenoh** [comment]
Currently not building because of issues in master, but other than that is ready for initial review (want to get it in since there is a soft freeze, I will work on doing additional configuration later)

**Comment by mortenoh** [comment]
The SonarCloud error should not be relevant here as we are creating the connection factory as a bean for spring to use.

**Review by jbee — APPROVED** [review]
Looks good!

**Comment by jbee** [comment]
> The SonarCloud error should not be relevant here as we are creating the connection factory as a bean for spring to use.

Then you can login to SonarCloud (click the 1 Bug link in the report) and mark the issue as "won't fix" with the short explanation that it is a bean.

**Review by larshelge — APPROVED** [review]

**Pull request merged**
