### PR TITLE
Api tests travis check

### PR DESCRIPTION
**Pull request by vilkg**

### CODE REVIEW

**Comment by vilkg** [comment]
@amcgee with this I am introducing arg for additional maven params - can you check it out?

**Comment by amcgee** [comment]
@vilkg this looks fine to me!  We could think about explicitly enabling a "skipTests" switch in the future, but I think this is great for now :-)

**Comment by vilkg** [comment]
Yep, but in this case I also needed -q flag, since travis limits log size per job 👍

**Comment by jason-p-pickering** [comment]
Can one of the admins verify this patch?

**Comment by stian-sandvold** [comment]
Closing PR after discussion with @vilkg . A different approach is planned.

**Pull request closed without merging**
