### PR TITLE
feat: added version to new tracker URL path [DHIS2-12255]

### PR DESCRIPTION
**Pull request by gnespolino**
new tracker endpoint should now support version in URL.

### CODE REVIEW

**Review by Bekkalizer — APPROVED** [review]

**Review by teleivo — APPROVED** [review]

**Comment by ameenhere** [comment]
We should not be supporting "DHIS version ALL" correct? And have it exclusively for 2.37 onwards onlu right?

**Comment by teleivo** [comment]
> We should not be supporting "DHIS version ALL" correct? And have it exclusively for 2.37 onwards onlu right?

Why?

**Review by ameenhere — APPROVED** [review]

**Comment by teleivo** [comment]
the PR status is stuck because semantic check does not respond/finish its check. does anyone of @gnespolino @ameenhere have admin/merge rights to merge anyway?

**Comment by gnespolino** [comment]
> the PR status is stuck because semantic check does not respond/finish its check. does anyone of @gnespolino @ameenhere have admin/merge rights to merge anyway?

I don't

**Pull request merged**
