### PR TITLE
Added test class for SmsUtils (SmsUtilsTest) with tests for all methods.

### PR DESCRIPTION
**Pull request by RRGWhite**

### CODE REVIEW

**Review by stian-sandvold — CHANGES_REQUESTED** [review]
Hi @RRGWhite ,

thanks for the contribution. However it seems our codestyle is not applied to your PR. Could you fix the codestyle issues? The codestyle files can be found in the root folder of the project.

The primary issue I see is that we use spaces between paranthesis and parameters: "( params, params )"

Thanks you!

**Comment by RRGWhite** [comment]
Hi @stian-sandvold 

Many thanks for reviewing the request. Apologies for the style issues, I did not see the guidelines. 

I have pushed a new commit which I believe should rectify the issues.

Thanks!

**Comment by RRGWhite** [comment]
Hi @stian-sandvold 

Do you need me to make any further changes for this request to be merged?

Many thanks!

**Comment by larshelge** [comment]
Hi @RRGWhite , many thanks, we really appreciate code contribution, in particular related to testing.

One last thing: We use 4 spaces and not 2 in the code style. Please fix and we can merge.

**Pull request merged**
