### PR TITLE
Fix login page favicon

### PR DESCRIPTION
**Pull request by mediremi**
Closes https://jira.dhis2.org/browse/DHIS2-9045

### CODE REVIEW

**Comment by amcgee** [comment]
@cooper-joe the favicon in DHIS2 core is the old icon (https://play.dhis2.org/dev/favicon.ico, [source](https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/favicon.ico)) - we should update it to the latest so that this change (thanks @mediremi) picks up the correct one.  This will be a temporary fix until we replace the web portal.

@larshelge @Philip-Larsen-Donnelly should we backport this?

Let's hold off on merging this until we update the favicon (@cooper-joe we can do it on this same branch) and determine if we should backport.  I created [DHIS2-10301](https://jira.dhis2.org/browse/DHIS2-10301) to track this.

**Review by amcgee — CHANGES_REQUESTED** [review]
The change to `dhis-web-commons` looks good, but let's update the reference favicon.ico

**Comment by mediremi** [comment]
@amcgee I updated this `favicon.ico` https://github.com/dhis2/dhis2-core/blob/03b5fa0c6c403e9a8d618c4029a1e5abd61841eb/dhis-2/dhis-web/dhis-web-commons-resources/src/main/webapp/favicon.ico in this PR. Is there another one that I should update too?

**Comment by amcgee** [comment]
@mediremi no, that's correct - sorry I missed it.  To confirm it's the correct one, where did you pull it from?  App platform?

**Comment by mediremi** [comment]
@amcgee Yep got it from https://github.com/dhis2/app-platform/blob/210c9ccbd937cb70e23cbcbcb3a6f9ff7dd53314/shell/public/favicon.ico

**Comment by cooper-joe** [comment]
For reference, there's a [favicon package here](https://github.com/dhis2/dhis2-identity/tree/master/web/favicon_package). Looks like the one that's pulled from the app-platform is correct 👍.

**Review by amcgee — APPROVED** [review]
Looks good to me!  Need a review from backend team to merge, let's discuss possible backports in the Jira issue

**Review by larshelge — APPROVED** [review]

**Pull request merged**
