### PR TITLE
fix: thread-safety and memory leakage in scheduling manager

### PR DESCRIPTION
**Pull request by jbee**
While working on #7711 I noticed 2 issues in the `SchedulingManager` that I initially fixed in that branch but decided to extract into a separate PR. Issues are:

* maps used to manage internal state were not thread-safe (state is potentially read and write by different threads)
* tasks added to the `currentTasks` map will never get removed. I added a completion stage so that they remove themselves once they are done. The state in the `currentTasks` map is only used by the class itself to recognised jobs already started so they are not started another time. It is not directly accessible to external code. Since the map holds the future of the result not clearing it from the map does hold on to the job result which I think over time must be considered a memory leak.

### CODE REVIEW

**Review by netroms — APPROVED** [review]

**Comment by larshelge** [comment]
Looks good to me. Do you think the test coverage is good enough as it is, or should we add a test?

**Comment by jbee** [comment]
Given that the existing dedicated tests are all `@Ignore`d some new tests might be a good idea.

**Review by vietnguyen — APPROVED** [review]

**Comment by stian-sandvold** [comment]
@jbee will you be adding tests to this PR, or will it be added at a later time? Ref. @larshelge 's comment. If later, you can go ahead and merge this PR :)

**Comment by jbee** [comment]
@stian-sandvold :+1:  I wanted to add them but I am busy in a larger feature branch. I can add them in a separate PR when I get there.

**Pull request merged**
