### PR TITLE
fix: Deletion of interpretation comments [DHIS2-8256]

### PR DESCRIPTION
**Pull request by maikelarabori**
Changing the collection type and sorting by comment id, so the many-to-many deletion works correctly.

Related DB migration PR: https://github.com/dhis2/wow-backend/pull/35

### CODE REVIEW

**Comment by larshelge** [comment]
Hey Maikel, just wondering, why did we have to change to Set for deletion to work?

**Comment by maikelarabori** [comment]
> Hey Maikel, just wondering, why did we have to change to Set for deletion to work?

Hey @larshelge, that was changed so I could remove the sort_order column (avoiding the NPE issue for sort_order gaps) and also because each comment is unique. A Set seems to better in this sense. Besides that, deleting many-to-many relationships backed by Lists is not something well supported by Hibernate in my view.

When we had Lists we were having constraint exceptions raised by Postgresql in the PK (interpretationid, sort_order) when deleting comments. Actually this relationship could be one-to-many as we cannot share the same comment across different interpretations (one interpretation has many comments).

Please let me know if it makes sense, or if you see possible issues if we switch to Set?

Thanks,
Maikel

**Comment by larshelge** [comment]
After discussions we will look for a way to avoid the model change and see if removal can be done as a "cascade" from Interpretation.

**Comment by stian-sandvold** [comment]
> After discussions we will look for a way to avoid the model change and see if removal can be done as a "cascade" from Interpretation.

Does this mean we can close this PR?

**Comment by maikelarabori** [comment]
> > After discussions we will look for a way to avoid the model change and see if removal can be done as a "cascade" from Interpretation.
> 
> Does this mean we can close this PR?

Hey @stian-sandvold, that's right. I'm closingit now.

Thanks for the remind! :+1:

**Pull request closed without merging**
