### PR TITLE
feat: DHIS2-10386:  Add a dash separator to ReportingRate name

### PR DESCRIPTION
**Pull request by maikelarabori**
Adding a dash to separate data set and report rate displayName.

### CODE REVIEW

**Review by enricocolasante — APPROVED** [review]

**Comment by jimgrace** [comment]
Hmmm. Why did you make this a long dash? The way I see it:

Long dash pros: It might look a bit better.

Long dash cons: If someone is searching in a log or a spreadsheet containing these names, and searches for a name using a regular dash, it may not work. Or if someone tries to break apart the name for some reason using a regular dash it may not work. I've done a few things with DHIS2 object names in spreadsheets, and this could have totally messed me up, at least until I figured out what was going on.

I think the regular dash might be a better choice, but I'm also interested to know why you changed to the long dash.

**Comment by maikelarabori** [comment]
> Hmmm. Why did you make this a long dash? The way I see it:
> 
> Long dash pros: It might look a bit better.
> 
> Long dash cons: If someone is searching in a log or a spreadsheet containing these names, and searches for a name using a regular dash, it may not work. Or if someone tries to break apart the name for some reason using a regular dash it may not work. I've done a few things with DHIS2 object names in spreadsheets, and this could have totally messed me up, at least until I figured out what was going on.
> 
> I think the regular dash might be a better choice, but I'm also interested to know why you changed to the long dash.

Thanks for the feedback @jimgrace. I agree that using a regular dash is simpler and more "usable".

The reason for changing it to a long dash was because of the frontend team requirements. They wanted to have a long dash as a separator.

I'm including @janhenrikoverland into the loop so he is aware of the possible cons above and can take a final decision.

**Comment by cooper-joe** [comment]
> Why did you make this a long dash?

The long dash was my suggestion, and it was purely based on reading the name in Data Visualizer app. This was intended to prevent the name looking like a formula where the dash (-) was a mathematical symbol. I figured using the correct typographic symbol (–) might avoid this.

However, as I said, this recommendation doesn't take into account that the symbol will actually be included in the object name, not just in the way it's displayed (We used the long dash when displaying Program attributes, for example, but then they are not part of the object name). As @jimgrace describes, it sounds like using the long dash could cause some serious issues. So, in light of that, I think it makes sense to stick with the original symbol and not use a long dash.

**Comment by maikelarabori** [comment]
> > Why did you make this a long dash?
> 
> The long dash was my suggestion, and it was based on the name display in Data Visualizer app. This was intended to prevent the name looking like a formula where the dash (-) was a mathematical symbol. I figured using the correct typographic symbol (–) might avoid this. It is also consistent with the way we display additional information, like Program, for other items.
> 
> However, as I said, this recommendation doesn't take into account that the symbol will actually be included in the object name, not just in the way it's displayed (We used the long dash when displaying Program attributes, for example, but then they are not part of the object name). As @jimgrace describes, it sounds like using the long dash could cause some serious issues. So, in light of that, I think it makes sense to stick with the original symbol and not use a long dash.

Thanks for the clarification @cooper-joe, I am reverting the changes in a few minutes so we keep the regular dash.

Cheers,
Maikel

**Comment by maikelarabori** [comment]
Hi @jimgrace, we reverted to regular dash. Please have a look.

Thanks,
Maikel

**Comment by jimgrace** [comment]
@maikelarabori and @cooper-joe Thanks for the responses on the long vs. regular dashes. Joe, what you said makes a lot of sense. I didn't realize they were used elsewhere in the front end. I'm not sure the long dashes would ever cause problems, but they might. I appreciate the discussion, and the reversion to regular dashes. Thanks.

**Review by jimgrace — APPROVED** [review]

**Pull request merged**
