### PR TITLE
Fix SQL query invalid error

### PR DESCRIPTION
**Pull request by chathurawidanage**
SQL Views, on creating gives a false query error if the table columns used for the query contains the restricted keywords. 

ie : lastUpdated in events

### CODE REVIEW

**Comment by larshelge** [comment]
Agree we can do a better job here. However this approach is a bit simplistic as we want to prevent against e.g. "delete from dataelement;".

**Comment by chathurawidanage** [comment]
Then this can't be easily solved without using a SQL parser, right? I would like to work this out, if it is OK to include additional dependency. Or can;t this be solved by just checking few expected cases? This is a critical problem in our DHIS2 based application.

**Comment by jason-p-pickering** [comment]
Why not make it easy and change the name of the property to 'modfied' in
line with other objects?

**Comment by chathurawidanage** [comment]
lastUpdated is an build in attribute using throughout the DHIS2 (int DataValues, Events, etc..) if I am not mistaken. Any way thanks. Our issue is only with update keyword. We will try to apply a local fix for that. Thanks.

**Comment by jason-p-pickering** [comment]
Right. But why not just change it. We use "created". Why not just used
"modified"?

 Else apply a better regex approach if that's deemed too invasive.

**Comment by chathurawidanage** [comment]
Thanks. I'll try your suggestions.

**Pull request closed without merging**
