### PR TITLE
fix: Counting only accessible category option events [DHIS2-7712]

### PR DESCRIPTION
**Pull request by maikelarabori**
This fix aims to count events related to the category options that the currently logged user is allowed to read.
Today, we are counting all events without any kind of checking, so even events that the user is not permitted to read are being considered and counted.

**I'm not sure if this is a fix or a feature, or even if this is the desirable behaviour, but the users are really asking for it, as can be seen in the comments on DHIS2-7712.**

The solution will add a new object (QueryExclusion) to the DataQueryParams and this new object will be used later on in the flow at querying time, so the "exclusions" will not be part of the query.
If we have similar cases in the future, we can simply add a new "exclusion" and handle it down the flow.

### CODE REVIEW

**Review by stian-sandvold — APPROVED** [review]
I am not sure myself how the intended logic should be here. @larshelge needs to chime in :)

**Comment by maikelarabori** [comment]
Hi @larshelge ,

could you have a look at this PR?

Many thanks

**Review by jimgrace — CHANGES_REQUESTED** [review]
Hi @maikelarabori,

- When `UserCredentials` are configured, they may be assigned _dimension constraints_ of `Set<CategoryOptionGroupSet> cogsDimensionConstraints` and/or `Set<Category> catDimensionConstraints`. The purpose of these is to determine if and how `CategoryOption` read access is checked during analytics. This is entirely for performance, to avoid checking `CategoryOption` access for every user on every installation. This is especially useful when there are many category options (such as in PEPFAR, see below) and a user is allowed to see all of them; this avoids checking all of them. `UserCredentials.getDimensionConstraints()` returns any constraints of both of these types. For this ticket, dimension constraints should be checked only if they are configured for the user.

- On systems with many category options that are selectively shared with many users, it's probably most likely that each user could either see all the category options or a small number of them. This means that a query filter (when needed) might want to restrict the results to the shared options rather than eliminating all the non-shared options. For example, the PEPFAR _Funding Mechanism_ Category has 6000+ options. Of the users who are not assigned to all the options, many are assigned only to 1 option, and many others to a small number of them. Users who can see all the options have no dimension constraints configured, so they don't need any filter.

- `DefaultAnalyticsSecurityManager.withUserConstraints( EventQueryParams params )` already calls `applyDimensionConstraints()` to check these dimension constraints where they exist, and return a new `EventQueryParams` that filters for them if/as appropriate. I believe this ticket could be satisfied by adding the single line:

        params = securityManager.withUserConstraints( params );

in `DefaultEventAnalyticsService.getAggregatedEventData`, after the call to `securityManager.decideAccessEventQuery` and before the call to `queryValidator.validate`. This follows the pattern in `AbstractAnalyticsService.getGrid( EventQueryParams params )`.

I tried this and it seems to work. But I suggest that you try it too, and see if this approach is lacking anything.

- The other part of the PR should be to write or extend a unit test so that it fails without the fix and succeeds with it. :)

**Comment by maikelarabori** [comment]
Thanks for your detailed comments and suggestions @jimgrace.
I'm making the changes in another branch and once that is ready I will assign you as a reviewer.

Cheers,
Maikel

**Pull request closed without merging**
