### PR TITLE
fix: hard delete ProgramInstance when deleting Program

### PR DESCRIPTION
**Pull request by enricocolasante**
ProgramInstance is soft deleted when a TEi is deleted but it is hard deleted when a program is deleted.
I changed the code to make everything as it was before this PR
https://github.com/dhis2/dhis2-core/pull/5131

Anyway, it would be good to have a discussion around this soft/hard deletion for ProgramInstance

### CODE REVIEW

**Comment by stian-sandvold** [comment]
I think we should have this discussion before we merge this PR. it seems to me that we will now hard-delete psi when deleting program, which is not what we wont. We want to block deletion of metadata which has data.

**Comment by stian-sandvold** [comment]
After discussion with Enrico, the problem this PR seeks to resolve, was caused by another bug, which will be fixed separately. this PR will be closed.

**Comment by enricocolasante** [comment]
Actually, the fix is going to be done on top of the changes of this branch, so I am going to reopen the PR

**Comment by larshelge** [comment]
One question is, do we want to introduce the concept of "hard delete" in the method naming?

So far we have a concept of "soft delete", meaning we have "deleteX" and "softDeleteX".

Should we keep it like this, so that we have "deleteProgramInstance" and "softDeleteProgramInstance"?

**Comment by enricocolasante** [comment]
The concept introduced in the previous PR is that we have some objects that are soft deletable (and by consequence all the others to be hard deletable).
In the case of ProgramInstance we have a peculiar behaviour because it is soft deletable when deleting a TEI and hard deletable when deleting a Program.

This PR is introducing some technical debt that will need to be solved with a wider solution around the whole hard/soft delete logic.
If we can accept this debt, we can then solve it in https://jira.dhis2.org/browse/DHIS2-8557.

**Comment by larshelge** [comment]
Okay thanks, that is fair enough.

**Pull request merged**
