### PR TITLE
feat: Username and OrgUnit valueType preheat suppliers [TECH-452]

### PR DESCRIPTION
**Pull request by abyot**

### CODE REVIEW

**Review by stian-sandvold — APPROVED** [review]

**Review by luciano-fiandesio — APPROVED** [review]
Would be good perhaps to add a couple of unit test of for the suppliers (using mockito).

**Comment by larshelge** [comment]
@abyot Could you please add a name/description to the PR?

**Comment by abyot** [comment]
> @abyot Could you please add a name/description to the PR?

@larshelge  - done.

**Comment by abyot** [comment]
> Would be good perhaps to add a couple of unit test of for the suppliers (using mockito).

@luciano-fiandesio - was thinking the same. the thing is these suppliers are not really doing much just make a call to a service which I added a unit test.

**Pull request merged**
