### PR TITLE
fix: Interpretation link for event visualization [DHIS2-13109]

### PR DESCRIPTION
**Pull request by maikelarabori**
Incorrect URL in messaging app when mentioning interpretation in the Line Listing app.

**_NEEDS APPROVAL FROM THE RELEASE CONTROL TEAM._**

### CODE REVIEW

**Comment by larshelge** [comment]
@maikelarabori should we backport this to 2.38, I assume the new line listing app will not be available by default in 2.38?

**Comment by maikelarabori** [comment]
> @maikelarabori should we backport this to 2.38, I assume the new line listing app will not be available by default in 2.38?

@janhenrikoverland, by our conversation it should go into 2.38 I guess. Or maybe I misunderstood?

**Review by gnespolino — APPROVED** [review]

**Comment by janhenrikoverland** [comment]
In my opinion it can wait for 38.1 and then we can point it to the LL app.

Alternatively it can point to ER. Then new stuff won't work, however pivot tables will not work in LL. There's no good solution here really.

**Comment by maikelarabori** [comment]
@larshelge / @janhenrikoverland,
per the discussion above, I'm closing this PR and we will leave it for 2.38.1.

Thanks,
Maikel

**Pull request closed without merging**
