### PR TITLE
fix: Sharing section is missing in program access page

### PR DESCRIPTION
**Pull request by vietnguyen**
https://jira.dhis2.org/browse/DHIS2-10464

Issue: 
1) An api request with `fields=owner` doesn't return legacy sharing properties ( publicAccess, userAccesses, userGroupAccesses ). This is because we removed those properties as a part of introducing new jsonb sharing column.
2) Legacy `UserAccess` and `UserGroupAccess` have a displayName attribute, this is taken from userGroup displayName or user displayName.  But we are now only save user/userGroup uid  in the jsonb sharing column. So those attributes are returned null.

Fix: 
~~Temporary add those legacy sharing properties to the owner properties list. Will need to remove this after front-end app make use of new jsonb sharing.~~  Birk agreed to change the request with sharing attributes explicitly instead of `owner`
2) Add cache for user/userGroup displayName and add them to the response in `FieldFilterService`.  This cache is also used in `SharingController`

### CODE REVIEW

**Review by jbee — COMMENTED** [review]
Before I do a deeper review I wonder if this been discussed? I feel this is the wrong approach to address the issue, especially if we long term don't want the display name in the access objects.

My thoughts would be to more do some hack in the controller layer to add/resolve display names from acess UIDs in case we have this situation.

**Comment by vietnguyen** [comment]
> Before I do a deeper review I wonder if this been discussed? I feel this is the wrong approach to address the issue, especially if we long term don't want the display name in the access objects.
> 
> My thoughts would be to more do some hack in the controller layer to add/resolve display names from acess UIDs in case we have this situation.

- I think later we do need to keep this displayName, but add it to the new `sharing` column instead of legacy access objects. So front-end won't have to do another request for object's displayName. 
- I'm afraid putting this hack to the controller layer may introduce overhead .. Since we have to do loops through object properties and do all the checks again.
- Another reason is that there are controllers which don't extend `AbstractCrudController` but only use `FieldFilterService` ( eg. `DataApprovalController`, `EventController`, `ProgramDataElementController` .. ) so we would need to add this hack to multiple controllers.

**Review by jbee — COMMENTED** [review]
Code looks fine. I still think it is the wrong solution to make all this effort in the backend to provide the frontend with a display name. To me it appears the correct solution is to use a different query in the frontend - worst case use an extra query. @larshelge WDYT?

**Review by mortenoh — APPROVED** [review]

**Review by jbee — APPROVED** [review]
As said, I did not realise this is patching a legacy model.

**Pull request merged**
