### PR TITLE
2.31 Fix bug keep sending ping request after logged in data entry app

### PR DESCRIPTION
**Pull request by vietnguyen**

### CODE REVIEW

**Comment by Philip-Larsen-Donnelly** [comment]
I checked out and built this PR, then put the war on a remote server (so that I could disconnect) but I still see the pings continue at 10s intervals after the connection is re-established. i.e. the test still fails.

**Comment by vietnguyen** [comment]
@Philip-Larsen-Donnelly did you try to clear the browser cache ?

**Comment by Philip-Larsen-Donnelly** [comment]
I didn't think that would be necessary as I created a whole new instance. But I can try!...

**Comment by vietnguyen** [comment]
@Philip-Larsen-Donnelly I have tested it again on my local, the issue is fixed. The browser may cache the old script.. maybe need to clear the cache, close the browser and open new incognito window. Please make sure the new script is loaded as in below screenshot, using browser developer tools, in Sources tab. 
Screen Shot 2019-03-22 at 4 46 17 PM

**Comment by larshelge** [comment]
Will this apply to 2.29 and 2.30 as well @vietnguyen  ?

**Comment by vietnguyen** [comment]
@larshelge  yes, I'm back porting it down to 2.29, just waiting for Philip to confirm this fix work on his side.

**Comment by vietnguyen** [comment]
@larshelge  yes, I'm back porting it down to 2.29, just waiting for Philip to confirm this fix work on his side.

**Comment by Philip-Larsen-Donnelly** [comment]
Tried on incognito browser with all caches cleared.

image

The very first ping you see it on loading the app. There are no pings after that until I disconnect the network and type something into a field.
After that I get the pings in red every 10s.
When I reconnect the network I get the pings with the 200 status; but still every 10 seconds.

**Comment by Philip-Larsen-Donnelly** [comment]
@vietnguyen thanks for pointing out that it's not on play/2.31dev yet, doh!
Anyway, I retested on the original instance I created from the PR (above) https://play.dhis2.org/phil
I still see the continuous pings.

**Comment by vietnguyen** [comment]
@Philip-Larsen-Donnelly I have just update the fix. What happened is that I tested this by stopping my local server, while you disconnect your client. Those are two has different results. Please check again with new code when you have time. Thanks

**Comment by Philip-Larsen-Donnelly** [comment]
Tested successfully on the latest PR build - following both approaches; disconnect network AND stop/start server.

**Pull request merged**
