### PR TITLE
fix: (2.35) Process SMS when phoneNumber is not linked to originator [DHIS2-9941]

### PR DESCRIPTION
**Pull request by zubaira**

### CODE REVIEW

**Review by amcgee — CHANGES_REQUESTED** [review]
@zubaira let's discuss this with the security team before merging

**Review by maikelarabori — APPROVED** [review]
Assuming it's working fine and there are no security concerns, it looks good to me :+1:

**Comment by zubaira** [comment]
> @zubaira let's discuss this with the security team before merging

@amcgee we had a meeting about this. Can you please approve it. Hisp Uganda has been waiting for this fix.
Thanks

**Review by enricocolasante — APPROVED** [review]

**Review by amcgee — APPROVED** [review]
@zubaira sorry for the delay- as we agreed in the security meeting, this is not a regression so we should merge it.  We also want to improve and rethink security of these endpoints in the near future.

Note- I am approving this but have not reviewed the code, @maikelarabori did that!

**Pull request merged**
