### PR TITLE
WIP chore: one Dockerfile

### PR DESCRIPTION
**Pull request by teleivo**
Please forgive my ignorance 🙂 I might totally be missing a requirement/reason why the docker images are built the way they are. I would love to know all about it 😄 This might still be an interesting approach we could leverage.

Dockers multi-stages can be used to have one single Dockerfile where depending on the current need for example only the debian or alpine image is built. Dockers experimental builder (has been experimental for some years now ;) ) https://docs.docker.com/develop/develop-images/build_enhancements/ can run stages concurrently and not run unused stages.

With this change it will build the debian image by default

```sh
docker build . --tag dhis/core:debian
```

or a specific tomcat debian image
```sh
docker build --tag <image> --build-arg DEBIAN_TOMCAT_IMAGE=tomcat:8.5.34-jre8-alpine .
```

(here the alpine stage will not run with buildkit)

and the alpine image like so (either with the default tomcat alpine image or a specific one)

```sh
docker build . --tag dhis/core:alpine --target alpine
docker build --tag <image> --target alpine --build-arg ALPINE_TOMCAT_IMAGE=tomcat:8.5.34-jre8-alpine .
```

### Resources I found helpful
- https://medium.com/@tonistiigi/advanced-multi-stage-build-patterns-6f741b852fae

### CODE REVIEW

**Comment by teleivo** [comment]
So I was able to get the `build-containers.sh` to work
I for example ran

```sh
 ./docker/build-containers.sh dhis2/core-dev:2.36 2.36
```

which only builds the base once for the first image in the `containers-list.sh` and then builds the rest of the images super fast 🎊 

```
⏵ dhis2-core git:(docker-one-dockerfile) docker images
REPOSITORY         TAG                                     IMAGE ID       CREATED          SIZE
dhis2/core-dev     2.36-tomcat-8.0-jre8-slim               14550ed515e5   3 minutes ago    968MB
dhis2/core-dev     2.36-tomcat-8.5-jdk11-openjdk-slim      14550ed515e5   3 minutes ago    968MB
dhis2/core-dev     2.36-tomcat-8.5-jdk8-openjdk-slim       14550ed515e5   3 minutes ago    968MB
dhis2/core-dev     2.36-tomcat-8.5.34-jre8-alpine          14550ed515e5   3 minutes ago    968MB
dhis2/core-dev     2.36-tomcat-8.5.46-jdk8-openjdk-slim    14550ed515e5   3 minutes ago    968MB
dhis2/core-dev     2.36-tomcat-8.5.47-jdk11-openjdk-slim   14550ed515e5   3 minutes ago    968MB
dhis2/core-dev     2.36-tomcat-9.0-jdk11-openjdk-slim      14550ed515e5   3 minutes ago    968MB
dhis2/core-dev     2.36-tomcat-9.0-jdk8-openjdk-slim       14550ed515e5   3 minutes ago    968MB
dhis2/core-dev     2.36-tomcat-9.0.27-jdk11-openjdk-slim   14550ed515e5   3 minutes ago    968MB
```

What's missing is the requirement to reuse a war. I will have a look. I do wonder if in some cases it would be better to just build/reuse the base.

Are we building the jenkins agents ourselves? What docker version do they run? I would be interested to see if we could use buildkit on jenkins. That would be awesome 😄

**Comment by teleivo** [comment]
@vilkg you said the api tests run slower which I do not think 😅 the API test workflow previously compiled the war  outside of docker and then used the `artifacts/` logic to put it into the docker image while building it. now the war is simply built in docker. You can also see that the timings of API tests vary https://github.com/dhis2/dhis2-core/actions/workflows/run-api-tests.yml?query=is%3Asuccess sometimes there around 15m, sometimes 17m (which was already true before this change).

Is there a reason we are using the debian image for running the API tests? We could use the alpine image which is smaller, which could speed things up 😄

**Comment by vilkg** [comment]
> Are we building the jenkins agents ourselves? What docker version do they run? I would be interested to see if we could use buildkit on jenkins. That would be awesome 😄

We are, I'm not sure about the version on the new agents. @radnov can answer I'm sure. The agents are short-lived. They are recreated for every build, so if you are thinking of buildkit's cacheing advantage, that might be harder to achieve :)

**Comment by teleivo** [comment]
Thank you very much @varl for all your input and beautiful breakdown! And @vilkg for your help and spotting of errors/shortcomings as well 😄 

Is it correct to say that the checksum logic is only in place because we allow for copying a war into the docker build? I would argue that that is not needed if you package the war inside a docker stage and copy it into another stage. Integrity is given in that case.

I would like to challenge the custom war file 😋 
> Important for local development in environments that do not have the full Java tool chain.

That's where Docker shines. All you need is in the docker and the rest is taken care of. If you already have docker installed, you can package up the war.

To the other point of getting the war out of published docker images. I would not encourage that. If you want a specific release download it from here https://releases.dhis2.org/ which is also a good place for putting checksums. Specifically, because the docker build and its artifacts are not encouraged to be used in production. Docker images as I understand it are provided as a convenience for development. Production grade artifacts are the wars at https://releases.dhis2.org/. At least that's how I understand it.

So if you want a war visit: https://releases.dhis2.org/
If you want a docker image for development visit: https://hub.docker.com/u/dhis2


Maybe just for completeness here are some advantages I collected with one  multi-stage Dockerfile:

Using Docker (or any tool) in its documented form (by that I mean Dockerfile's without custom copy & extract logic)
* allows new joiners to understand the Docker build ASAP. New joiners can reuse their previous knowledge. New joiners without prior Docker experience can learn by reading the Docker documentation and find help by searching the web
  for answers to issues, others had building/running Docker.
* It also reduces the risk of a custom build that is only well understood by a
  few to be lost when the most knowledgeable people on this topic leave.
* allows us to take advantage of all improvements coming to Docker like
  BuildKit => faster builds
* removes cognitive load by having less indirection. `docker build ...` and that's it
* allows us to reuse in this case the Dockerfile in all kinds of scenarios by
  simply calling the `docker build` tool tuned to that specific use case (on
  developers machines, on Jenkins, in a GitHub action, ...)

I am planning to give buildkit on github actions soon a try and see if we can reproduce the reduced build times in for example the api-tests.

I will incorporate the structural changes 👍🏻 For the custom war I would still like to challenge it before doing the acrobatics 👯

**Comment by vilkg** [comment]
The custom war file is useful when: 
- we want to build war once and share it across multiple steps in the pipeline - deploy to releases.dhis2.org, put into the docker images and deploy to docker hub and etc. 
- during development - building war without excluding unit tests and etc. 
- in GH actions - building outside docker ( I am still not convinced that building inside docker will be faster than outside) 

>Specifically, because the docker build and its artifacts are not encouraged to be used in production. Docker images as I understand it are provided as a convenience for development. Production grade artifacts are the wars at https://releases.dhis2.org/. At least that's how I understand it.

There are implementations using docker in prod. We had feature requests coming in, like running dhis2 process as non-root. Wars in docker images should be the same as in releases.dhis2.org.

**Comment by teleivo** [comment]
> > I think this use case is already covered with this change. `docker build . --tag asdf` will build only your changes into the docker image. This can then be used in your `d2` command.
> 
> Great. +1
> 
> I suppose I can use `docker save custom | gzip | ssh user@host docker load` to transfer the image from my workstation to my development server./
Not sure about the specifics of your setup. This might be too much but you could also use a docker registry and push/pull from it

**Comment by vilkg** [comment]
Before your change, build-dev was building war and then transferring that war to the image. Now, it's just building the base image. That in itself is adding time to the build. That's what I mean ;)

**Pull request closed without merging**
