### PR TITLE
fix: Grid Caching is not properly used in analytics [2.37-DHIS2-TECH-842]

### PR DESCRIPTION
**Pull request by d-bernat**
/api/analytics/dataValueSet.json?dimension=dx:SqD0kovH0CS&dimension=ou:m5NxCAOnDg6&dimension=pe:20210902  where dx is a program indicator returns null value, when the request is issued second time and more within AnalyticsCache TTL 
(typically 60sec)

first response:
```json
{
    "dataValues": [
        {
            "dataElement": "SqD0kovH0CS",
            "period": "20210902",
            "orgUnit": "m5NxCAOnDg6",
            "value": "2.0",
            "storedBy": "[aggregated]",
            "created": "2021-11-23",
            "lastUpdated": "2021-11-23",
            "comment": "[aggregated]"
        }
    ]
}
```
second one: 
```json
{
    "dataValues": [
        {
            "dataElement": "SqD0kovH0CS",
            "period": "20210902",
            "orgUnit": "m5NxCAOnDg6",
            "value": "null",
            "storedBy": "[aggregated]",
            "created": "2021-11-23",
            "lastUpdated": "2021-11-23",
            "comment": "[aggregated]"
        }
    ]
}
```

The problem was identified in the caching of analytics Grid object:

this is object coming to cache:
[dy, ou, pe, value]
[SqD0kovH0CS, m5NxCAOnDg6, 20210902, 2.0]

first get:
[dy, ou, pe, value]
[SqD0kovH0CS, m5NxCAOnDg6, 20210902, null, null, 2.0]

second one:
[dy, ou, pe, value]
[SqD0kovH0CS, m5NxCAOnDg6, 20210902, null, null, null, null, 2.0]

We are caching the grid and modifying it later within one single request. Because this is in memory cache inside the runtime JVM, only reference is cached, there is no serialization on the way. After the caching, cached object is modified (add two rows for coc and aoc). Within the next request we modified already modified object so the grid is not readable correctly anymore until the cache expiration. 

The solution is to modify AnalyticsCache to get back the clone of cached grid instead of grid (reference) itself.

### CODE REVIEW

**Comment by d-bernat** [comment]
Test scenario:
1. Repeat within one  minute this request: http://localhost:8080/dhis/api/analytics/dataValueSet.json?dimension=dx:SqD0kovH0CS&dimension=ou:m5NxCAOnDg6&dimension=pe:20210902
2. You should see always this response: 
```json
{
    "dataValues": [
        {
            "dataElement": "SqD0kovH0CS",
            "period": "20210902",
            "orgUnit": "m5NxCAOnDg6",
            "value": "2.0",
            "storedBy": "[aggregated]",
            "created": "2021-11-23",
            "lastUpdated": "2021-11-23",
            "comment": "[aggregated]"
        }
    ]
}
```
**Environment: TEST,
!do not forget to modify host in http request**

**Review by jbee — COMMENTED** [review]
I feel like this is more of a quick fix. As I understand this the `Grid` implementation should not be a mutable object as it is already aggregated data, correct? In such a case I'd say the correct way to fix this is to make all `Grid` implementations read-only (use `@Builder` and getters only) and fix the place that would set value to `null` for some reason so it can do its work with a copy. lomboks `toBuilder()` might be useful to make a copy with a changed `value`.

**Review by stian-sandvold — APPROVED** [review]

**Comment by d-bernat** [comment]
> I feel like this is more of a quick fix. As I understand this the `Grid` implementation should not be a mutable object as it is already aggregated data, correct? In such a case I'd say the correct way to fix this is to make all `Grid` implementations read-only (use `@Builder` and getters only) and fix the place that would set value to `null` for some reason so it can do its work with a copy. lomboks `toBuilder()` might be useful to make a copy with a changed `value`.



> I feel like this is more of a quick fix. As I understand this the `Grid` implementation should not be a mutable object as it is already aggregated data, correct? In such a case I'd say the correct way to fix this is to make all `Grid` implementations read-only (use `@Builder` and getters only) and fix the place that would set value to `null` for some reason so it can do its work with a copy. lomboks `toBuilder()` might be useful to make a copy with a changed `value`.

Hey Jan, the assumption  is not correct. As it is implemented now, Grid has to be mutable. In the class DataAggregatorGrid there is a method getAggregatedDataValueGrid. There are sequential steps to fill the grid with the data. In the mid of this worklow the temporary state of the grid is cached (dataHandler.addProgramDataElementAttributeIndicatorValues). 
Anyway, there is a possibility to use this cache on the beginning and the end of this process. But I chose change of the grid cache to return clone and protect cached object, cause grid itself can't be immutable.

**Review by jbee — APPROVED** [review]
Sounds like we could make this read-only by using the builder as I said. But you are most likely right about a bigger refactoring. Nonetheless I think this should like we should look into that. I can put it on my list if you want.

**Comment by d-bernat** [comment]
> Sounds like we could make this read-only by using the builder as I said. But you are most likely right about a bigger refactoring. Nonetheless I think this should like we should look into that. I can put it on my list if you want.
Thank's a lot Jan. I put it in analytics backlog (https://jira.dhis2.org/browse/TECH-861) and it will be resolved as a technical debt by backend analytics  team

**Comment by d-bernat** [comment]
> Sounds like we could make this read-only by using the builder as I said. But you are most likely right about a bigger refactoring. Nonetheless I think this should like we should look into that. I can put it on my list if you want.

Thank's a lot @jbee . I put it in analytics backlog (https://jira.dhis2.org/browse/TECH-861) and it will be resolved as a technical debt by backend analytics team

**Comment by larshelge** [comment]
Thanks for looking into this! Clearly a bug and a problem in the design.

@jbee I agree that immutability is often good, though in this particular case it might not be ideal. The grid is really meant to be built up over time and passed around. Making copies of it for every time data is added will be expensive since the grid is meant to hold data and could hold a lot of data potentially. Would be similar to `CopyOnWriteArrayList` which has overhead.

**Comment by larshelge** [comment]
Thanks for looking into this! Clearly a bug and a problem in the design.

@jbee I agree that immutability is often good, though in this particular case it might not be ideal. The grid is really meant to be built up over time and passed around. Making copies of it for every time data is added will be expensive since the grid is meant to hold data and could hold a lot of data potentially. Would be similar to `CopyOnWriteArrayList` which has overhead.

**Comment by larshelge** [comment]
Though I suspect this is not the real cause @d-bernat . We do create a new Grid on every request (`DataAggregator` line 85) and cache it with the query params as the (immutable) key, and then return immediately after, so how can the grid be modified later? Perhaps there is a race condition in the caching code (I think there is), though it sounds like you make these requests not in parallel?

**Comment by larshelge** [comment]
I might reading this wrongly, but this looks like a request for aggregated data in the data value set format, for which it seems we don't actually use the analytics cache at all?

https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java#L135

**Comment by larshelge** [comment]
I think if this is reproducible and not a race condition we should add a test here to verify the behavior.

**Comment by d-bernat** [comment]
> I think if this is reproducible and not a race condition we should add a test here to verify the behavior.

Ok, I will add unit test to test the cached object is well protected and merge it

**Pull request merged**
