### PR TITLE
fix: Zero values for analytics with AVERAGE (2.37) [DHIS2-12497]

### PR DESCRIPTION
**Pull request by SferaDev**

### CODE REVIEW

**Comment by larshelge** [comment]
Looks good. Please update branch, and tag https://jira.dhis2.org/browse/DHIS2-12497 in the title.

**Comment by SferaDev** [comment]
Done

**Comment by larshelge** [comment]
Sorry it seems branch got out of date again for some reason, would you mind updating the branch again @SferaDev ?

**Comment by SferaDev** [comment]
Done again

**Pull request merged**
