### PR TITLE
(2.31) Remove "-SNAPSHOT" from version strings

### PR DESCRIPTION
**Pull request by alanthing**
Change "2.31-SNAPSHOT" to "2.31" since 2.31 has been released.

### CODE REVIEW

**Comment by Philip-Larsen-Donnelly** [comment]
Thanks for this @alanthing, but I'm going to close this PR as we will move to a slightly different model with patch releases now. I will push a PR to set the version to 2.31.1-SNAPSHOT until we release 2.31.1 patch. (The patch will have version 2.31.1, then the branch will move to version 2.31.2-SNAPSHOT).

**Comment by alanthing** [comment]
Makes sense; I understand wanting to keep `-SNAPSHOT` in the version string between released versions, but please remove it for 2.31.0, 2.31.1, etc. The DHIS2 downloads page for 2.31.0 links to https://s3-eu-west-1.amazonaws.com/releases.dhis2.org/2.31/2.31.0/dhis.war and this file contains `2.31-SNAPSHOT` as the version. 

The following is in a fresh `centos:7` container:

```
$ yum -d0 -e1 -y install unzip

$ curl -O https://s3-eu-west-1.amazonaws.com/releases.dhis2.org/2.31/2.31.0/dhis.war

$ unzip -d dhis -qq dhis.war

$ cd dhis

$ find WEB-INF/lib -maxdepth 1 -type f -name 'dhis-service-core-2.*.jar'
WEB-INF/lib/dhis-service-core-2.31-SNAPSHOT.jar

$ unzip -q -p WEB-INF/lib/dhis-service-core-2.31-SNAPSHOT.jar build.properties
build.version = 2.31-SNAPSHOT
build.time = 2019-01-14 10:19:32
build.revision = ddf2ea2
jasperreports.version = 6.3.1
```

The API is the same:

```
$ yum -d0 -e1 -y install epel-release

$ yum -d0 -e1 -y install jq

$ curl --user admin:district -s https://play.dhis2.org/2.31.0/api/system/info | jq '{version:.version,buildTime:.buildTime,revision:.revision,jasperReportsVersion:.jasperReportsVersion}'
{
  "version": "2.31-SNAPSHOT",
  "buildTime": "2018-11-30T20:18:22.000",
  "revision": "ddf2ea2",
  "jasperReportsVersion": "6.3.1"
}
```

As such, we are unable to reliably determine if systems running 2.31 or higher are running a stable released version or an unstable revision between stable versions.

**Comment by Philip-Larsen-Donnelly** [comment]
Yes, I'm sorry for the error with the initial 2.31.0 release. We will transition the versions correctly from now, and 2.31.1, onwards (we hope to release patch 2.31.1 in the next couple of weeks). At the moment we don't plan to retrospectively correct 2.31.0.

**Comment by Philip-Larsen-Donnelly** [comment]
By the way, you can use the revision hash to reliably identify the 2.31.0 stable release - it will always be ddf2ea2 as  in your output; whereas the unstable versions will be different. Then from 2.31.1 on the version should be set correctly, and can be used.

**Pull request closed without merging**
