### PR TITLE
fix: Fix paging issue in UserController [DHIS2-10135]

### PR DESCRIPTION
**Pull request by vietnguyen**
- Add skipPaging for in memory engine. 
- `queryService.query(line 182)` in `UserController.getEntityList` should not apply paging if filter parameter is empty
- `userStore.getUserCount` should not apply paging parameters
- Add e2e api test

### CODE REVIEW

**Comment by larshelge** [comment]
I am wondering if this was done to achieve field filtering? Then maybe we got paging twice on in the process?

**Comment by mortenoh** [comment]
This code is needed if you mix in-memory and persistent queries, if we remove the paging will be wrong for mixed queries

**Comment by vietnguyen** [comment]
> This code is needed if you mix in-memory and persistent queries, if we remove the paging will be wrong for mixed queries, it does have a performance impact.. and we should look into better ways of doing this when we upgrade our user* model/services

Ok, so can we add a skipPaging flag for the in memory query engine ? So it won't do the paging second time.

**Comment by larshelge** [comment]
@mortenoh Right, but the paging is not working properly now. The "custom" user query service is doing paging on its own. So I assume doing paging again in memory should not be done?

**Comment by mortenoh** [comment]
Ok, please try it.. with testing, luciano spent a lot of time fixing some of the issues there (not sure if that was just with general metadata or users also), @vietnguyen just make sure it works when you do mixed (it might changed, but i thought here we did 2 queries, one using userService to query the real objects, then through the in-memory query service to allow additional filters, but if thats not true anymore feel free to remove yes)

**Comment by vietnguyen** [comment]
@larshelge @mortenoh  Updated the fix now, please check again

**Review by larshelge — APPROVED** [review]

**Comment by larshelge** [comment]
Works for me.

**Pull request merged**
