### PR TITLE
fix: Slow PSQL queries when retrieving /events [ DHIS2-12039 ]

### PR DESCRIPTION
**Pull request by lucaCambi77**
This is an attempt to improve performance while accessing /events endpoint.
An index has been added to programstageinstance table for **lastupdated** column, which is ordering the result set.

Main reasons for this attempt :
1) This is significantly reducing the cost of the queries
2) During local performance tests, the distribution of the response time during around 5 minutes has moved a bit to lower percentiles and reduced the average response time over a much higher Request per second.
Locally psi table is not big as in a production env though, so results need to be validated

Also, a minor update not to retrieve a full Tei for existence

### CODE REVIEW

**Comment by teleivo** [comment]
@lucaCambi77 I think it would be helpful if you would post some numbers/summary from your local performance tests. Descriptions like `a bit lower`, `much higher` do not tell us much. Adding an index also comes with a cost. So that should be warranted.

@vilkg can we run the changes from this branch on the setup you have with a bigger dataset? To validate this does improve things before we merge the changes.

**Comment by lucaCambi77** [comment]
@teleivo I am not able to post an HTML report as it is not supported here. There are some improvements locally, we just need to test if this makes improvements in a bigger dataset. If not we can just revert the change.

**Comment by teleivo** [comment]
> @teleivo I am not able to post an HTML report as it is not supported here. There are some improvements locally, we just need to test if this makes improvements in a bigger dataset. If not we can just revert the change.

you can upload a picture of the HTML 😄

**Comment by lucaCambi77** [comment]
It is a report with different parts, not easy to take a pic. Let's see if there is an improvement. If we can avoid merging first it is of course better

**Comment by vilkg** [comment]
> 
> @vilkg can we run the changes from this branch on the setup you have with a bigger dataset? To validate this does improve things before we merge the changes.

yeah, Luca already asked me. We will. :)

**Review by enricocolasante — APPROVED** [review]

**Comment by vilkg** [comment]
I have compared dev and this branch and I can't see any significant improvements with the requests that I'm trying ( from the issue description). The sql queries also look identical. @lucaCambi77

**Comment by lucaCambi77** [comment]
yes @vilkg the query is the same, only a new index has been added. We'll try something different

**Review by larshelge — APPROVED** [review]

**Pull request closed without merging**
