### PR TITLE
feat: Category option in indicators [DHIS2-716-2.37]

### PR DESCRIPTION
**Pull request by d-bernat**

### CODE REVIEW

**Comment by d-bernat** [comment]
Operands in indicators are based on data element and category option combos. The goal of the user story is deliver ability to calculate the aggregated values for category options as well. The idea behind the solution is:
1. Change dhis2-antlr-expression-parser template: extend the grammar for parsing #{dataelement.co:categoryoption} (see https://github.com/dhis2/dhis2-antlr-expression-parser/pull/24)

2. Database changes: 

- add the column category option to the dataelementoperand table and assign categoryoptionid to the dataelementid
- add two columns to analytics table (cao - category option, ato - attribute option)
- populate those values to the analytics
**this has to be discussed, cause there is a trade off between  a) put the load on population process or b) on the collecting the aggregated data, this solution is based on a) and can be relative easily changed**

3.

**Comment by jimgrace** [comment]
Hi Dusan, here is an expanded version of what we discussed today on Zoom.

Each data value has one or more category options. We can't just add a category option column "cao" in analytics, because a single data value can have multiple options. However, we do have a "category option combo" column in analytics, because each data value will have only one category option combo that represents the combination of all the options for that data value.

I was thinking that before the analytics database calls, we could expand a category option to a collection of all the category option combos (COCs) having that category option. Then when analytics database tables are queried, we specify that the COC must be in that collection of values: SQL "co in (...)". We could use this same technique again for DHIS2-9747 where we can specify a list of category option groups ("coGroup:"). Likewise, we can expand the set of category option groups into a set of category option combos belonging to that group, so the analytics query part would be the same.

For DHIS2-9747, we can also expand a data element group ("deGroup:") into a collection of data elements, and use that in the analytics query.

Here's how I think we should process a parsed category option, and some of the key classes along the way:

#### DimItemDataElementAndOperand
This gets called when the parser finds '#{'. If it's a category option, you will need to put that UID inside
some DimensionalItemId (either of type DATA_ELEMENT_OPERAND or some other type). And we need to remember that it is a category option.

#### DimensionalItemId
This holds the UID(s) for different types of objects. It will need to know when it has a category option rather than a category option combo.

#### DefaultDimensionService
The methods getDataDimensionalItemObjectMap and getNoAclDataDimensionalItemObjectMap take a Set of DimensionalItemId and find the corresponding DimensionalItemObject through database queries. They do this in three steps: (1) getAtomicIds gets the IDs of the "atomic" metadata DimensionalItemIds from the DimensionalItemIds. For example a DataElementOperand is a compound object in that it reduces to the atomic object DataElement, optionally a CategoryOptionCombo, and optionally another CategoryOptionCombo used as the attributeOptionCombo. (2) get from the database all the atomic objects of each atomic class. This is done in a single query each atomic object type for performance reasons. Previously they were fetched one at a time and it was a big performance bottleneck especially for a collection of validation rules that may have hundreds or thousands of terms total. (I wrote the current code to avoid this.) (3) getItemObjectMap assembles the final set of DimensionalItemObject from the atomic DimensionalItemObject objects.

I have been thinking that during this translation from DimensionalItemId to DimensionalItemObject, a category option in the DimensionalItemId could be looked up as an "atomic" object, and the resulting set of category option combos could be added to the resulting DimensionalItemObject. On second thought (see below), we could just add the CategoryOption to the DimensionalItemObject, and use its getCategoryOptionCombos() for the analytics query.

#### DimensionalItemObject
Some class that implements this interface (either DataElementOperand or another class) should be extended so that it can hold the set of category option combos inferred by the selected category option.

So the main design question in my mind is how best to represent the category option in a DimensionalItemObject class, and in a DimensionalItemId type. Possibilities for the DimensionalItemObject include:

1. `DataElementOperand`. Advantage is that it's already used for a DataElement and CategoryOptionCombo, and is already the receptor of '#{' information. Disadvantage is that it is used for other things as well, like data sets and charts, where it is persisted in the database as just a DataElement and CategoryOptionCombo, but not attributeOptionCombo, and not anything else new that we might add.

2. Create a new subclass of `DataElementOperand`. Advantage is that it doesn't further overload the things we use DataElementOperand for. Disadvantage is that it's a new thing, which is also confusing. If we do this, we might always parse '#{' into this class (even things that could otherwise go into DataElementOperand). Or we could use this class only when CategoryOption is specified, and use DataElementOperand when we don't have a CategoryOption.

3. Create an entirely new class that implements `DimensionalItemObject`. Advantage is that DataElementOperand is the least confused by the new options. Disadvantage is that it's also a new thing, and that it might be confusing as to when to use DataElementOperand and when to use this new thing.

4. Currently there is a periodOffset field in both DimensionalItemId and DimensionalItemObject. I expect in the future we will add other query modifiers as well, and perhaps create a new class for them, perhaps QueryModifiers. This object would contain periodOffset, and it could contain other things as well, possibly even including CategoryOption.

The more I think about this, the more I think that using `DataElementOperand` may be the best. I think I would start writing the code this way. If you get into too much trouble with existing uses of DataElementOperand, know that the others are possible too. But my guess is that DataElementOperand will be the best.

After thinking more about the code, I suggest implementing CategoryOption only in place of the categoryOptionCombo, and not also in place of the attributeOptionCombo, because: (a) the requirement is only for categoryOptionCombo, and (b) it looks like it would be a fair bit of extra code to support both. I'd say keep it simple and only do what is required. This also simplifies the parser grammar; there is only one place where the CategoryOption UID must be parsed.

I think we don't need to add any more TotalType enum values. When a CategoryOption is specified, this should be the same as specifying a categoryOptionCombo, for the purpose of determining the TotalType.

So I suggest adding a `String categoryOptionId` to DimensionalItemId, and a `CategoryOption categoryOption` to DataElementOperand. When the query is done in analytics, if there is a CategoryOption, you can filter by the collection of CategoryOptionCombos found in categoryOption.getCategoryOptionCombos().

Don't hesitate to contact me if you have any questions about this, or if other issues come up.

**Review by jimgrace — CHANGES_REQUESTED** [review]
(See long comment).

**Comment by d-bernat** [comment]
There is another version of PR

**Pull request closed without merging**
